### ISSUE TITLE
Suggestion: indicate order of keys to type using shades of colour

### ISSUE THREAD

**Issue by yalu** [emp3ror/typali#4]
Indicate order of keys to type in a sequence by using shades of colour.

For example, most saturated shade indicates the first key to press, least saturated last, and everything in between.

**Comment by emp3ror** [comment]
Highlighted the single letter and other letters differently

**Comment by yalu** [comment]
sweet!!!

finally I can learn typing in Nepali.

Thanks! @emp3ror 💯
